engines:
  haxe-checkstyle:
    enabled: true
  csslint:
    enabled: false
  markdownlint:
    enabled: false

exclude_paths:
  - manual/**/*

ratings:
  paths:
    - "**.hx"
    - "**.css"
    - "**.md"
