version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - HAXEORG_DB_HOST=dbHost
      - HAXEORG_DB_PORT=3306
      - HAXEORG_DB_USER=dbUser
      - HAXEORG_DB_PASS=dbPass
      - HAXEORG_DB_NAME=haxe
  dbHost:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=haxe
      - MYSQL_USER=dbUser
      - MYSQL_PASSWORD=dbPass
    volumes:
      - database:/var/lib/mysql
volumes:
  database: {}